# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField(verbose_name='Date Added')),
                ('year_released', models.IntegerField(default=0)),
            ],
        ),
    ]
